### ISSUE TITLE
Post-processing

### ISSUE THREAD

**Issue by SDAASDDASD** [temf/bembel#18]
are the plottings for stress fields, strain fields, user-defined outputs supported in "bembel"?

**Comment by flx-wlf** [comment]
You may use specializations of the Potential class to implement the evaluation of custom quantities dependent on the solution of the boundary integral equation. For this, take a look at the specializations in the Laplace folder as an example. With regards to plotting, we do support user-defined outputs to the VTK file format. This is showcased in the files examples/example_VTK*.cpp.
