### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by debasishuiuc** [temf/bembel#35]
dd@maths:~/Desktop/hpcsoft/bembel/build $ pkg-config --modversion eigen3
3.2.92

I have Eigen3 installed. cmake works fine. But make does not. Please help.

dd@maths:~/Desktop/hpcsoft/bembel/build $ make debug
[100%] Switch CMAKE_BUILD_TYPE to Debug
-- 

                         ,;:cclloooooooodddddddoolc;, 
                      .cc::::::;;;;;;;,,,,,,;;;;::c:,.             
                  ...'lkc',;;::::::::::::::::;;,'..,cd;            
              ';:::::::dOdllccc::::::::;;;:::ccloddoll'            
            ,ll,..     'oc.',,,,;;;;;;;;;;;;,,''''lk:              
          .:o,      ...'okdooollllllllllllllllllookd.              
         .co.    .;cc::cxx'                      .oo.              
         ,d;    .ol.    ;d,                       co.              
         :o.    :o.    .ll.  .:lo;.               'll'             
         co.    co.  .cll;..ckOxdc'....            .,lc.           
         ;d,    ,d;.cOx:od:dkollodO00Ok:.            .:o;.         
         .ll.   .:xkOOkkxloxoxkl,'lk0XX0:              'oc.        
          'oc.  .:kl..'dkkkdOk;'coxO0XXKl.              .ol.       
           .ll'.;d:...',l00O0c.,kXXXXXKk,                'o:       
            .;ooxo.'d00kooOKO;  'lxkko;.   .              :d'      
              .ckc.:kkxO0OkKKc .;okOx;.;ldxxdl.           'd:      
               'd:.,ll::coOKKx';O0o:;ckKKK00K0o.          .oc      
               .oc;kKXK0xl:lkOll0x. ,k0o;,,;:c;.          .oc       
               .lock0xoodxxocllcxd'.lOc..,oxOOOd:.        'd;      
                ,d:,coxxdddddl:':o;.lo..l0XXXXXXKd.       co.      
                .lo'c00occcloddl:cc;::.:0KklcxKXXOc;'    .o:       
                 .oll0d. ':,',:lol::;'.o0o.  :OOkdOKl.  .co.       
                  'odxk:.oK0c..:cc;,...lO:   .,';xOl.  .:d,        
                   'oddkk0KXk,;dxdol:'.'dd'  ,xlok:.;,.;d;         
                    'oo:lxOkc..;ldxkkkxlldd;.'xddd;lkc;d:.         
                     .ol.... .dKKkdxOKXK0OOOkdkkkxdkkxx:.          
                      .ll.   .ckk:;dOKOdc,,;:ldOKKK0Okc.           
                       .ll.    ...'cokkdccdxdlloxxOOOl.            
                        .ol.         ...'cl;':dl;codl.             
                         ;ko;'....         ..,:;;lxx,              
                         cxlclooolllllllllllllllccdx'              
                         ,lc:;,,''''''''''''',,;;:l:.              
                          ..,;:::::::::::::::::;,'.                

	
This is Bembel, the higher order C++ boundary element library. It was 
written as part of a cooperation of J. Doelz, H. Harbrecht, S. Kurz, 
M. Multerer, S. Schoeps, and F. Wolf at Technische Universitaet Darmstadt,
Universitaet Basel, and Universita della Svizzera italiana, Lugano. This
source code is subject to the GNU General Public License version 3 and
provided WITHOUT ANY WARRANTY, see <http://www.bembel.eu> for further
information.

-- Found -march=native, adding option to builds of type >release< only
-- Found -flto, adding option to builds of type >release< only
-- Found -fopenmp, adding option to builds of type >release< only
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dd496/Desktop/hpcsoft/bembel/build
[  2%] Building CXX object examples/CMakeFiles/example_VTKDomainExport.out.dir/example_VTKDomainExport.cpp.o
In file included from /home/dd496/Desktop/hpcsoft/bembel/Bembel/ClusterTree:24:0,
                 from /home/dd496/Desktop/hpcsoft/bembel/Bembel/AnsatzSpace:19,
                 from /home/dd496/Desktop/hpcsoft/bembel/Bembel/IO:24,
                 from /home/dd496/Desktop/hpcsoft/bembel/examples/example_VTKDomainExport.cpp:1:
/home/dd496/Desktop/hpcsoft/bembel/Bembel/src/ClusterTree/ElementTreeNode.hpp:117:20: error: enclosing class of constexpr non-static member function ‘double Bembel::ElementTreeNode::get_h() const’ is not a literal type
   constexpr double get_h() const { return 1. / double(1 << level_); }
                    ^
/home/dd496/Desktop/hpcsoft/bembel/Bembel/src/ClusterTree/ElementTreeNode.hpp:21:7: note: ‘Bembel::ElementTreeNode’ is not literal because:
 class ElementTreeNode {
       ^
/home/dd496/Desktop/hpcsoft/bembel/Bembel/src/ClusterTree/ElementTreeNode.hpp:21:7: note:   ‘Bembel::ElementTreeNode’ has a non-trivial destructor
/home/dd496/Desktop/hpcsoft/bembel/Bembel/src/ClusterTree/ElementTreeNode.hpp:118:17: error: enclosing class of constexpr non-static member function ‘int Bembel::ElementTreeNode::get_level() const’ is not a literal type
   constexpr int get_level() const { return level_; }
                 ^
examples/CMakeFiles/example_VTKDomainExport.out.dir/build.make:62: recipe for target 'examples/CMakeFiles/example_VTKDomainExport.out.dir/example_VTKDomainExport.cpp.o' failed
make[6]: *** [examples/CMakeFiles/example_VTKDomainExport.out.dir/example_VTKDomainExport.cpp.o] Error 1
CMakeFiles/Makefile2:175: recipe for target 'examples/CMakeFiles/example_VTKDomainExport.out.dir/all' failed
make[5]: *** [examples/CMakeFiles/example_VTKDomainExport.out.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/debug.dir/build.make:57: recipe for target 'CMakeFiles/debug' failed
make[3]: *** [CMakeFiles/debug] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/debug.dir/all' failed
make[2]: *** [CMakeFiles/debug.dir/all] Error 2
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/debug.dir/rule' failed
make[1]: *** [CMakeFiles/debug.dir/rule] Error 2
Makefile:129: recipe for target 'debug' failed
make: *** [debug] Error 2

**Comment by flx-wlf** [comment]
Indeed, constexpr member functions are a C++14 feature. Depending on your compiler, it might be enough to enable C++14 features.  If your compiler does not have full C++14 support, a work around would be to redeclare the functions as const instead of constexpr.  However, as we only want to require C++11, we should change this. @muchip @jdoelz  do you agree?

**Comment by flx-wlf** [comment]
@debasishuiuc which compiler and OS do you use?

**Comment by debasishuiuc** [comment]
I did not specify a particular compiler, so it must have used the default one. I am using it on the office cluster, where they have a few different ones installed. 

g++      g++-4.7  g++-5 
gcc             gcc-ar-4.7      gcc-nm-4.7      gcc-ranlib-5
gcc-4.7         gcc-ar-5        gcc-nm-5        
gcc-5           gccmakedep      gcc-ranlib      
gcc-ar          gcc-nm          gcc-ranlib-4.7

**Comment by flx-wlf** [comment]
As it turns out, we are C++11 conforming, and this issue is due to a compiler bug, see [here on Stackoverflow](https://stackoverflow.com/questions/36489369/constexpr-non-static-member-function-with-non-constexpr-constructor-gcc-clang-d) and [here on openstd](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1684). According to a reply on the Stackoverflow thread, the issue seems to have been fixed for gcc with version 7.2. I am afraid we cannot accommodate for known and fixed compiler bugs, so I will close the issue. However, the workaround of removing the constexpr's from the methods mentioned in your warnings should work for your compilers.
