### ISSUE TITLE
Rhino

### ISSUE THREAD

**Issue by OVGULIU** [temf/bembel#6]
Dear Professors and Colleagues,

 can we directly use Rhino export file in further releases?

Kind regards.

**Comment by coffeedrinkingpenguin** [comment]
Hi OVGULIU,

we are always looking to add additional functionality and a Rhino import would be a very nice feature. Unfortunately, we currently lack the resources to implement this. However, as a quick fix, you can already interface through iges files (which are Rhino compatible) and the NURBS toolbox. I will close the issue for now.

Best regards!

**Comment by OVGULIU** [comment]
Dear Prof. Wolf,

thanks very much for  your detailed reply. 

Kind regards!
